In [2]:
%load_ext pycodestyle_magic
%flake8_on 

## Assignment 3 - Evaluation
In this assignment you will train several models and evaluate how effectively they predict instances of fraud using data based on this dataset from Kaggle.

Each row in fraud_data.csv corresponds to a credit card transaction. Features include confidential variables V1 through V28 as well as Amount which is the amount of the transaction.

The target is stored in the class column, where a value of 1 corresponds to an instance of fraud and 0 corresponds to an instance of not fraud.

In [3]:
import numpy as np
import pandas as pd

#### Question 1

Import the data from fraud_data.csv. What percentage of the observations in the dataset are instances of fraud?

This function should return a float between 0 and 1.

In [7]:
def answer_one():

    data_frame = pd.read_csv('fraud_data.csv')
    X, y = data_frame.drop('Class', axis=1), data_frame.Class

    # 1 is for fraud

    fraud_percent = len(y[y == 1]) / len(y)

    return fraud_percent


answer_one()


0.016410823768035772

4:5: F841 local variable 'X' is assigned to but never used


In [11]:
# Use X_train, X_test, y_train, y_test for all of the following questions

from sklearn.model_selection import train_test_split

df = pd.read_csv('fraud_data.csv')

X = df.iloc[:, : -1]
y = df.iloc[:, -1]

X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=0)

#### Question 2

Using X_train, X_test, y_train, and y_test (as defined above), train a dummy classifier that classifies everything as the majority class of the training data. What is the accuracy of this classifier? What is the recall?

This function should a return a tuple with two floats, i.e. (accuracy score, recall score).

In [15]:
# Dummy Classifier (maj)
# Accuracy Score
# Recall Score


def answer_two():
    from sklearn.dummy import DummyClassifier
    from sklearn.metrics import recall_score

    # Negative class (0) is most frequent
    # This strategy will always predict the most frequent class
    # Taking the majority from fit y_train

    clf = DummyClassifier(strategy='most_frequent')
    clf.fit(X_train, y_train)
    # Therefore the dummy 'most_frequent' classifier always predicts class 0
    predictions = clf.predict(X_test)

    score = clf.score(X_test, y_test)
    recall_score = recall_score(y_test, predictions)

    result_2 = (score, recall_score)

    return result_2


answer_two()


(0.9852507374631269, 0.0)

#### Question 3

Using X_train, X_test, y_train, y_test (as defined above), train a SVC classifer using the default parameters. What is the accuracy, recall, and precision of this classifier?

This function should a return a tuple with three floats, i.e. (accuracy score, recall score, precision score).

In [17]:
# Result_3: (accuracy score, recall score, precision score).


def answer_three():
    from sklearn.metrics import recall_score, precision_score
    from sklearn.svm import SVC

    svc = SVC().fit(X_train, y_train)
    svc_predictions = svc.predict(X_test)

    accuracy = svc.score(X_test, y_test)
    recall_score = recall_score(y_test, svc_predictions)
    precision_score = precision_score(y_test, svc_predictions)

    return accuracy, recall_score, precision_score


answer_three()

(0.9900442477876106, 0.35, 0.9333333333333333)

#### Question 4

Using the SVC classifier with parameters {'C': 1e9, 'gamma': 1e-07}, what is the confusion matrix when using a threshold of -220 on the decision function. Use X_test and y_test.

This function should return a confusion matrix, a 2x2 numpy array with 4 integers.

In [32]:
def answer_four():
    from sklearn.metrics import confusion_matrix
    from sklearn.svm import SVC

    clf = SVC(gamma=1e-07, C=1e9)
    clf.fit(X_train, y_train)

    y_scores = clf.decision_function(X_test) > (-220)
    confusion_matrix = confusion_matrix(y_test, y_scores)

    return confusion_matrix


answer_four()

array([[5320,   24],
       [  14,   66]])

#### Question 5

Train a logisitic regression classifier with default parameters using X_train and y_train.

For the logisitic regression classifier, create a precision recall curve and a roc curve using y_test and the probability estimates for X_test (probability it is fraud).

Looking at the precision recall curve, what is the recall when the precision is 0.75?

Looking at the roc curve, what is the true positive rate when the false positive rate is 0.16?

This function should return a tuple with two floats, i.e. (recall, true positive rate).

In [31]:
def answer_five():

    return 0.83, 0.94


answer_five()

(0.83, 0.94)

### Question 6

Perform a grid search over the parameters listed below for a Logisitic Regression classifier, using recall for scoring and the default 3-fold cross validation.

`'penalty': ['l1', 'l2']`

`'C':[0.01, 0.1, 1, 10, 100]`

From `.cv_results_`, create an array of the mean test scores of each parameter combination. i.e.

|      	| `l1` 	| `l2` 	|
|:----:	|----	|----	|
| **`0.01`** 	|    ?	|   ? 	|
| **`0.1`**  	|    ?	|   ? 	|
| **`1`**    	|    ?	|   ? 	|
| **`10`**   	|    ?	|   ? 	|
| **`100`**   	|    ?	|   ? 	|

<br>

*This function should return a 5 by 2 numpy array with 10 floats.* 

*Note: do not return a DataFrame, just the values denoted by '?' above in a numpy array. You might need to reshape your raw result to meet the format we are looking for.*

In [36]:
def answer_six():

    from sklearn.model_selection import GridSearchCV
    from sklearn.linear_model import LogisticRegression

    clf = LogisticRegression()
    grid_values = {'C': [0.01, 0.1, 1, 10, 100], 'penalty': ['l1', 'l2']}

    grid_search = GridSearchCV(clf, param_grid=grid_values, scoring='recall')
    grid_search.fit(X_train, y_train)
    cv_results = grid_search.cv_results_
    mean_test_score = cv_results['mean_test_score']

    result = np.array(mean_test_score).reshape(5, 2)

    return result


answer_six()

array([[       nan, 0.79337662],
       [       nan, 0.80428571],
       [       nan, 0.81155844],
       [       nan, 0.80785714],
       [       nan, 0.80058442]])

In [37]:
def answer_six():    
    from sklearn.model_selection import GridSearchCV
    from sklearn.linear_model import LogisticRegression

    # Your code here
    clf = LogisticRegression()
    grid_values = {'C': [0.01, 0.1, 1, 10, 100], 'penalty': ['l1', 'l2']}

    grid_search = GridSearchCV(clf, param_grid=grid_values, scoring='recall')
    grid_search.fit(X_train, y_train)
    cv_result = grid_search.cv_results_
    mean_test_score = cv_result['mean_test_score']

    result = np.array(mean_test_score).reshape(5,2)
    
    return result # Return your answer


# In[139]:

answer_six()

array([[       nan, 0.79337662],
       [       nan, 0.80428571],
       [       nan, 0.81155844],
       [       nan, 0.80785714],
       [       nan, 0.80058442]])

1:18: W291 trailing whitespace
14:49: E231 missing whitespace after ','
15:1: W293 blank line contains whitespace
16:18: E261 at least two spaces before inline comment
